PRAGMA foreign_keys=OFF;--> statement-breakpoint
CREATE TABLE `__new_sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`agent_id` text NOT NULL,
	`organization_id` text,
	`created_by_user_id` text,
	`agent_version_id` text,
	`agent_snapshot` text,
	`environment_id` text,
	`environment_version_id` text,
	`environment_snapshot` text,
	`title` text,
	`env` text DEFAULT '{}' NOT NULL,
	`env_from` text DEFAULT '[]' NOT NULL,
	`volumes` text DEFAULT '[]' NOT NULL,
	`volume_mounts` text DEFAULT '[]' NOT NULL,
	`project_id` text NOT NULL,
	`durable_object_name` text NOT NULL,
	`sandbox_id` text,
	`pi_runtime_id` text,
	`pi_process_id` text,
	`runtime_endpoint_path` text,
	`model_provider` text,
	`model_config` text,
	`state` text NOT NULL,
	`state_reason` text,
	`active_turn_id` text,
	`turn_lease_expires_at` text,
	`continuation_depth` integer DEFAULT 0 NOT NULL,
	`metadata` text DEFAULT '{}' NOT NULL,
	`started_at` text,
	`closed_at` text,
	`archived_at` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL,
	FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`agent_version_id`) REFERENCES `agent_versions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`environment_id`) REFERENCES `environments`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`environment_version_id`) REFERENCES `environment_versions`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "ck_sessions_state" CHECK("__new_sessions"."state" in ('pending','running','idle','closed','error'))
);--> statement-breakpoint
INSERT INTO `__new_sessions` (
	`id`,
	`agent_id`,
	`organization_id`,
	`created_by_user_id`,
	`agent_version_id`,
	`agent_snapshot`,
	`environment_id`,
	`environment_version_id`,
	`environment_snapshot`,
	`title`,
	`env`,
	`env_from`,
	`volumes`,
	`volume_mounts`,
	`project_id`,
	`durable_object_name`,
	`sandbox_id`,
	`pi_runtime_id`,
	`pi_process_id`,
	`runtime_endpoint_path`,
	`model_provider`,
	`model_config`,
	`state`,
	`state_reason`,
	`active_turn_id`,
	`turn_lease_expires_at`,
	`continuation_depth`,
	`metadata`,
	`started_at`,
	`closed_at`,
	`archived_at`,
	`created_at`,
	`updated_at`
)
SELECT
	`id`,
	`agent_id`,
	`organization_id`,
	`created_by_user_id`,
	`agent_version_id`,
	`agent_snapshot`,
	`environment_id`,
	`environment_version_id`,
	`environment_snapshot`,
	`title`,
	`env`,
	`env_from`,
	`volumes`,
	`volume_mounts`,
	`project_id`,
	`durable_object_name`,
	`sandbox_id`,
	`pi_runtime_id`,
	`pi_process_id`,
	`runtime_endpoint_path`,
	`model_provider`,
	`model_config`,
	CASE WHEN `state` = 'stopped' THEN 'closed' ELSE `state` END,
	`state_reason`,
	`active_turn_id`,
	`turn_lease_expires_at`,
	`continuation_depth`,
	`metadata`,
	`started_at`,
	`stopped_at`,
	`archived_at`,
	`created_at`,
	`updated_at`
FROM `sessions`;--> statement-breakpoint
DROP TABLE `sessions`;--> statement-breakpoint
ALTER TABLE `__new_sessions` RENAME TO `sessions`;--> statement-breakpoint
CREATE INDEX `idx_sessions_project_state_created` ON `sessions` (`project_id`,`state`,`created_at`,`id`);--> statement-breakpoint
CREATE INDEX `idx_sessions_sandbox` ON `sessions` (`sandbox_id`);--> statement-breakpoint
PRAGMA foreign_keys=ON;
