// Package sessionevent provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.1 DO NOT EDIT.
package sessionevent

// Defines values for EnborSessionEventType.
const (
	EventTypeMessageCompleted    EnborSessionEventType = "message.completed"
	EventTypeMessageStarted      EnborSessionEventType = "message.started"
	EventTypeMessageUpdated      EnborSessionEventType = "message.updated"
	EventTypePermissionDenied    EnborSessionEventType = "permission.denied"
	EventTypePermissionRequested EnborSessionEventType = "permission.requested"
	EventTypePermissionResolved  EnborSessionEventType = "permission.resolved"
	EventTypeRuntimeCompleted    EnborSessionEventType = "runtime.completed"
	EventTypeRuntimeError        EnborSessionEventType = "runtime.error"
	EventTypeRuntimeStarted      EnborSessionEventType = "runtime.started"
	EventTypeTurnCompleted       EnborSessionEventType = "turn.completed"
	EventTypeTurnStarted         EnborSessionEventType = "turn.started"
	EventTypeUsageRecorded       EnborSessionEventType = "usage.recorded"
)

// Valid indicates whether the value is a known member of the EnborSessionEventType enum.
func (e EnborSessionEventType) Valid() bool {
	switch e {
	case EventTypeMessageCompleted:
		return true
	case EventTypeMessageStarted:
		return true
	case EventTypeMessageUpdated:
		return true
	case EventTypePermissionDenied:
		return true
	case EventTypePermissionRequested:
		return true
	case EventTypePermissionResolved:
		return true
	case EventTypeRuntimeCompleted:
		return true
	case EventTypeRuntimeError:
		return true
	case EventTypeRuntimeStarted:
		return true
	case EventTypeTurnCompleted:
		return true
	case EventTypeTurnStarted:
		return true
	case EventTypeUsageRecorded:
		return true
	default:
		return false
	}
}

// EnborSessionEventType defines model for EnborSessionEventType.
type EnborSessionEventType string
